<a href="https://colab.research.google.com/github/NairMpc/DataScience/blob/main/Assignment_4_BasicStats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BASIC STATISTICS-2

#Problem Statement : Hospital Patient Data Analysis

Context:

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

#Data Sets - Patient_Data  ,     Billing_Data

1.Load the patient dataset and show summary with info().

In [ ]:
import pandas as pd
p_df = pd.read_csv('Patient_Data.csv')
p_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [ ]:
p_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

Total entries: 6 (from index 0 to 5)
Total columns: 7

Column details:
PatientID: 6 non-null entries, int64 type

Name: 6 non-null entries, object type

Department: 6 non-null entries, object type

Doctor: 6 non-null entries, object type

BillAmount: 4 non-null entries, float64 type (indicates 2 missing values)

ReceptionistID: 6 non-null entries, int64 type

CheckInTime: 6 non-null entries, object type

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [ ]:
p_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [ ]:
p_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [ ]:
p_df.drop(['ReceptionistID', 'CheckInTime'], axis=1, inplace=True) # axis=1 drops columns.
p_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [ ]:
p_df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.	Remove duplicate patient records based on PatientID

In [ ]:
p_df.drop_duplicates(subset='PatientID', inplace=True)
p_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.	Fill missing BillAmount values with the mean bill amount.

In [ ]:
p_df.fillna(p_df['BillAmount'].mean(), inplace=True)
p_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

7.	Merge the billing dataset with patient dataset on PatientID.

In [ ]:
b_df = pd.read_csv('Billing_Data.csv')
b_df   # billing dataset

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [ ]:
p_df  # patient dataset

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [ ]:
# Merging both (b_df with p_df) first p_df, then b_df on PatientID
pd.merge(p_df, b_df, on='PatientID')

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [ ]:
# to create additional dataframe of patients, let us see the columns
p_df.columns
for col in p_df.columns:
    print(col)

PatientID
Name
Department
Doctor
BillAmount

In [ ]:
adtnl_p_df = pd.DataFrame({
    'PatientID': [105,106,107],
    'Name': ['Sari','Sudi','Kumar'],
    'Department': ['Cardiology','Neurology','Orthopedics'],
    'Doctor': ['Rukhu','Rajan','Pappu'],
    'BillAmount': [1000,2000,3000]
})
adtnl_p_df

   PatientID   Name   Department Doctor  BillAmount
0        105   Sari   Cardiology  Rukhu        1000
1        106   Sudi    Neurology  Rajan        2000
2        107  Kumar  Orthopedics  Pappu        3000

In [ ]:
# Now concatenate adtnl_p_df with p_df
pd.concat([p_df, adtnl_p_df], ignore_index=True)

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        105     Sari   Cardiology      Rukhu  1000.000000
6        106     Sudi    Neurology      Rajan  2000.000000
7        107    Kumar  Orthopedics      Pappu  3000.000000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [ ]:
b_df

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [ ]:
pd.concat([p_df,b_df[['InsuranceCovered','FinalAmount']]],axis=1)

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000