<a href="https://colab.research.google.com/github/NairMpc/DataScience/blob/main/Assignment_2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Assignment: Data Structures, Functions, Numpy & Pandas

#Section A: Data Structures & Control Structures

# 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
my_list = [5,10,15,20,25]
#1 append - adds one elemenent at end
my_list.append(30)
print(my_list)

[5, 10, 15, 20, 25, 30]

In [ ]:
#2.extend. extends a list at end
my_list.extend([35,40])
print(my_list)

[5, 10, 15, 20, 25, 30, 35, 40]

In [ ]:
#3. insert. insert at specified index
my_list.insert(0,5)
print(my_list)

[5, 5, 10, 15, 20, 25, 30, 35, 40]

In [ ]:
my_list.insert(len(my_list),55) # inserting at end , same as append
print(my_list)

[5, 5, 10, 15, 20, 25, 30, 35, 40, 55]

In [ ]:
my_list.remove(5) # remove first 5

In [ ]:
print(my_list)

[5, 10, 15, 20, 25, 30, 35, 40, 55]

In [ ]:
# remove element 30
my_list.remove(30)
print(my_list)

[5, 10, 15, 20, 25, 35, 40, 55]

In [ ]:
my_list.pop()  # remove lat element
print(my_list)

[5, 10, 15, 20, 25, 35, 40]

In [ ]:
my_list.pop()  # removes and shows the last element

40

In [ ]:
# clear()
my_list.clear()  # removes all elements ..and remain []
print(my_list)

[]

In [ ]:
# index
list1 = [10,'cat',15,20]
print(list1.index(15))
print(list1.index('cat'))

2
1

In [ ]:
list1.append('cat')

In [ ]:
# count
print(list1.count('cat'))

2

In [ ]:
# sort
# Let's re-initialize list1 to a list of integers to demonstrate sorting correctly.
list1 = [10, 5, 20, 15, 30] # Example: using only integers for sorting
list1.sort()
print(list1)

[5, 10, 15, 20, 30]

In [ ]:
list2 = ['cat', 'dog', 'apple', 'banana']
list2.sort(reverse=True)   # sort is in place
print(list2)

['dog', 'cat', 'banana', 'apple']

In [ ]:
# reverse
print(list1)
list1.reverse()  # reverse is inplace
print(list1)

[5, 10, 15, 20, 30]
[30, 20, 15, 10, 5]

#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
my_tuple = ('John', 'Jane', 'Bob')
my_tuple[1] = 'Alice'

TypeError: 'tuple' object does not support item assignment


The error TypeError: 'tuple' object does not support item assignment occurs because tuples are immutable data structures in Python. This means that after a tuple is created, you cannot change its elements, add new ones, or remove existing ones. The code is attempting to change the second element of my_tuple, which is not permitted. This property ensures data integrity and helps in cases where you need a collection of items that should not be altered.

## 3.	Create a set of integers with some duplicate values. Print the set and explain the output.`

In [ ]:
integer_set = {4,5,6,8,4,3,5,10,1} # set of integers with some duplicates
print(integer_set)

removed duplicate elements and displayed the remaining unique integers in arbitrary order because sets store only unique values and do not preserve insertion order.

#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
my_dict = {'name':'Koshy','age':25,'city':'Hyderabad'}  #dictionary with the keys: 'name', 'age', and 'city'
print(my_dict)

In [ ]:
my_dict['age'] = 33  # update age
my_dict['email'] = 'nairmpc@gmail.com' # add new key email
print(my_dict)

Adding and updating in a dictionary are similar operations.
In both cases, a value is assigned to a key using the same syntax.
If the key does not exist, the operation adds a new key–value pair;
if the key already exists, the operation updates the value by replacing the old one.

# 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [ ]:
print("Program to enter Name and age of a Person and Checks Voting Eligibility")
name = input("Enter Name: ")
age = int(input("Enter Age: "))

if age >= 18:
    print(name, "is eligible to vote")
else:
  print(f"As age of {name} is {age}(< 18), Not eligible to vote")

# 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [ ]:
print("Program to Enter marks of a Student and decides Grade")

try:
    marks = float(input("Enter Marks: "))

    if not (0 <= marks <= 100):
        print("Invalid marks! Enter a value between 0 and 100.")
    elif marks >= 90:
        print(f"Marks: {marks} Grade: A")
    elif marks >= 75:
        print(f"Marks: {marks} Grade: B")
    elif marks >= 50:
        print(f"Marks: {marks} Grade: C")
    else:
        print(f"Marks: {marks} Grade: Fail")

except ValueError:
    print("Invalid input! Please enter a numeric value.")

#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
try:
  number = float(input("Enter a number: "))

  if number > 0:
    if number % 2 == 0:
      print(f"{number} is positive and even.")
    else:
      print(f"{number} is positive")
  elif number == 0:
    print(f"The number is {number}")
  else:
    print(f"{number} is negative")

except ValueError:
  print("Invalid input! Please enter a valid number.")

# Section B: Numpy

#8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
import numpy as np
scalar = np.array(5)
print(scalar)

In [ ]:
array_1d = np.arange(1,6)
print(array_1d)

In [ ]:
one_d_array = np.array([1, 2, 3, 4, 5])
print(one_d_array)
print(one_d_array.ndim)

In [ ]:
two_d_array = np.arange(10, 61, 10).reshape(2, 3)
print(two_d_array)

#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
#method 1
four_four_array = np.random.randint(0, 101, size=(4, 4))
print(four_four_array)

In [ ]:
# two
list = []
for num in np.random.randint(0,100,16):
  list.append(num)
#print(list)
list_array = np.array(list).reshape(4,4)
print(list_array)

#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
array_3_3 = np.random.randint(0,100,size=(3,3))
print(array_3_3)
import pandas as pd
df = pd.DataFrame(array_3_3,columns=['A','B','C'])
print(df)

#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [ ]:
# As it says manually.
import pandas as pd
data_dictionary = {
    'Name':['Alice','Sara','Lakshmi','Koshy','Kumar','Vinu','Sari','Gokul','Kannan','Sabu'],
    'Age':[25,35,45,22,50,33,44,48,None,25,],
    'City':['Chennai','Bangalore','Mumbai','Hyderabad','Chennai','Bangalore','Indore','Hyderabad','Chennai','   '],
    'Salary':[50000,60000,70000,80000,0,100000,None,20000,50000,30000]
}
print(data_dictionary)
df = pd.DataFrame(data_dictionary)
print(df)

{'Name': ['Alice', 'Sara', 'Lakshmi', 'Koshy', 'Kumar', 'Vinu', 'Sari', 'Gokul', 'Kannan', 'Sabu'], 'Age': [25, 35, 45, 22, 50, 33, 44, 48, None, 25], 'City': ['Chennai', 'Bangalore', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore', 'Indore', 'Hyderabad', 'Chennai', '   '], 'Salary': [50000, 60000, 70000, 80000, 0, 100000, None, 20000, 50000, 30000]}
      Name   Age       City    Salary
0    Alice  25.0    Chennai   50000.0
1     Sara  35.0  Bangalore   60000.0
2  Lakshmi  45.0     Mumbai   70000.0
3    Koshy  22.0  Hyderabad   80000.0
4    Kumar  50.0    Chennai       0.0
5     Vinu  33.0  Bangalore  100000.0
6     Sari  44.0     Indore       NaN
7    Gokul  48.0  Hyderabad   20000.0
8   Kannan   NaN    Chennai   50000.0
9     Sabu  25.0              30000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     9 non-null      float64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

             Age         Salary
count   9.000000       9.000000
mean   36.333333   51111.111111
std    10.793517   31001.792063
min    22.000000       0.000000
25%    25.000000   30000.000000
50%    35.000000   50000.000000
75%    45.000000   70000.000000
max    50.000000  100000.000000

In [ ]:
df[['Name','City']]

      Name       City
0    Alice    Chennai
1     Sara  Bangalore
2  Lakshmi     Mumbai
3    Koshy  Hyderabad
4    Kumar    Chennai
5     Vinu  Bangalore
6     Sari     Indore
7    Gokul  Hyderabad
8   Kannan    Chennai
9     Sabu

In [ ]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [ ]:
df

      Name  Age       City  Salary
0    Alice   25    Chennai   50000
1     Sara   35  Bangalore   60000
2  Lakshmi   45     Mumbai   70000
3    Koshy   22  Hyderabad   80000
4    Kumar   50    Chennai       0
5     Vinu   33  Bangalore  100000
6     Sari   44     Indore   11000
7    Gokul   48  Hyderabad   20000
8   Kannan    0    Chennai   50000
9     Sabu   25              30000